/////////////////////////////////////////////////////////////////////
// Part of the UOV-Coprocessor artifact:
// https://github.com/flokrieger/UOV-Coprocessor
/////////////////////////////////////////////////////////////////////
//
// Derived from the UOV reference implementation (pqov):
// URL: https://github.com/pqov/pqov
// The AES-128-CTR based expansion of the public key follows pqov; the
// AES-128 block cipher itself follows FIPS 197.
//
// SPDX-License-Identifier: CC0-1.0 OR Apache-2.0
//
/////////////////////////////////////////////////////////////////////
//
// AES-128 and AES-128-CTR implementation in HLS. Used to expand the
// public key matrices P1 and P2 from the public key seed. Also used
// to sample the blinding matrices.
//
/////////////////////////////////////////////////////////////////////

#pragma once
#include <stdint.h>
#include "uov.h"

#define AES128_NRKEYS (11)

// 10-round AES-CTR implementation:
void aes128_keyschedule(const uint8_t key[16], uint8_t rkeys[AES128_NRKEYS][16]);
void aes128_encrypt_block(const uint8_t in[16], const uint8_t rkeys[AES128_NRKEYS][16], uint8_t out[16]);
void aes128_ctr_block(const uint8_t nonce[12], uint32_t ctr, const uint8_t rkeys[AES128_NRKEYS][16], uint8_t out[16]);

void computeRoundKeys(uint8_t seed_pk[16], uint8_t seed_blinding[16]);

// Return elements of P1 or P2 generated by AES-CTR
void getPElement(
    const bit_t p1_p2_sel,
    const bit_t do_blinding,
    const ap_uint<3> slice_idx,
    const addr_t row_idx,
    const addr_t col_idx,
    const addr_t uov_m,
    const addr_t uov_v,
    const uint32_t p1_bytes,
    uint8_t generated_elements[16]);
